package com.degstu.quickmoneycounter.currency

class CurrencyList {
    val list: Array<Currency> = arrayOf(
        /*

        Currency array format:
        Currency:
            name
            master symbol
            MP array common
            MP array uncommon
            MP array coins

         */

        //US Dollar
        Currency(
            "USD",
            "US Dollar",
            "$",
            arrayOf(
                MoneyPiece(
                    "USDPaper1",
                    1.0,
                    "$1"
                ),
                MoneyPiece(
                    "USDPaper5",
                    5.0,
                    "$5"
                ),
                MoneyPiece(
                    "USDPaper10",
                    10.0,
                    "$10"
                ),
                MoneyPiece(
                    "USDPaper20",
                    20.0,
                    "$20"
                )
            ),
            arrayOf(
                MoneyPiece(
                    "USDPaper2",
                    2.0,
                    "$2"
                ),
                MoneyPiece(
                    "USDPaper50",
                    50.0,
                    "$50"
                ),
                MoneyPiece(
                    "USDPaper100",
                    100.0,
                    "$100"
                )
            ),
            arrayOf(
                MoneyPiece(
                    "USDCoin1",
                    0.01,
                    "1\u00A2"
                ),
                MoneyPiece(
                    "USDCoin5",
                    0.05,
                    "5\u00A2"
                ),
                MoneyPiece(
                    "USDCoin10",
                    0.1,
                    "10\u00A2"
                ),
                MoneyPiece(
                    "USDCoin25",
                    0.25,
                    "25\u00A2"
                )
            )
        ),

        //euro
        Currency(
            "EUR",
            "Euro",
            "\u20AC",
            arrayOf(
                MoneyPiece(
                    "EURPaper5",
                    5.0,
                    "\u20AC5"
                ),
                MoneyPiece(
                    "EURPaper10",
                    10.0,
                    "\u20AC10"
                ),
                MoneyPiece(
                    "EURPaper20",
                    20.0,
                    "\u20AC20"
                )
            ),
            arrayOf(
                MoneyPiece(
                    "EURPaper50",
                    50.0,
                    "\u20AC50"
                ),
                MoneyPiece(
                    "EURPaper100",
                    100.0,
                    "\u20AC100"
                ),
                MoneyPiece(
                    "EURPaper200",
                    200.0,
                    "\u20AC200"
                ),
                MoneyPiece(
                    "EURPaper500",
                    500.0,
                    "\u20AC500"
                )
            ),
            arrayOf(
                MoneyPiece(
                    "EURCoin1",
                    0.01,
                    "1c"
                ),
                MoneyPiece(
                    "EURCoin2",
                    0.02,
                    "2c"
                ),
                MoneyPiece(
                    "EURCoin5",
                    0.05,
                    "5c"
                ),
                MoneyPiece(
                    "EURCoin10",
                    0.1,
                    "10c"
                ),
                MoneyPiece(
                    "EURCoin20",
                    0.2,
                    "20c"
                ),
                MoneyPiece(
                    "EURCoin50",
                    0.5,
                    "50c"
                ),
                MoneyPiece(
                    "EURCoin100",
                    1.0,
                    "\u20AC1"
                ),
                MoneyPiece(
                    "EURCoin200",
                    2.0,
                    "\u20AC2"
                )
            )
        ),

        //gbp
        Currency(
            "GBP",
            "Pound Sterling",
            "\u00A3",
            arrayOf(
                MoneyPiece(
                    "GBPPaper5",
                    5.0,
                    "\u00A35"
                ),
                MoneyPiece(
                    "GBPPaper10",
                    10.0,
                    "\u00A310"
                ),
                MoneyPiece(
                    "GBPPaper20",
                    20.0,
                    "\u00A320"
                )
            ),
            arrayOf(
                MoneyPiece(
                    "GBPPaper1",
                    1.0,
                    "\u00A31"
                ),
                MoneyPiece(
                    "GBPPaper50",
                    50.0,
                    "\u00A350"
                ),
                MoneyPiece(
                    "GBPPaper100",
                    100.0,
                    "\u00A3100"
                )
            ),
            arrayOf(
                MoneyPiece(
                    "GBPCoin1",
                    0.01,
                    "1p"
                ),
                MoneyPiece(
                    "GBPCoin2",
                    0.02,
                    "2p"
                ),
                MoneyPiece(
                    "GBPCoin5",
                    0.05,
                    "5p"
                ),
                MoneyPiece(
                    "GBPCoin10",
                    0.1,
                    "10p"
                ),
                MoneyPiece(
                    "GBPCoin20",
                    0.2,
                    "20p"
                ),
                MoneyPiece(
                    "GBPCoin50",
                    0.5,
                    "50p"
                ),
                MoneyPiece(
                    "GBPCoin100",
                    1.0,
                    "\u00A31"
                ),
                MoneyPiece(
                    "GBPCoin200",
                    2.0,
                    "\u00A32"
                ),
                MoneyPiece(
                    "GBPCoin3",
                    0.03,
                    "3p"
                ),
                MoneyPiece(
                    "GBPCoin4",
                    0.04,
                    "4p"
                ),
                MoneyPiece(
                    "GBPCoin6",
                    0.06,
                    "6p"
                ),
                MoneyPiece(
                    "GBPCoin25",
                    0.25,
                    "25p"
                )
            )
        ),

        //jpy
        Currency(
            "JPY",
            "Japanese Yen \u65E5\u672C\u5186",
            "\u00A5",
            arrayOf(
                MoneyPiece(
                    "JPYPaper1000",
                    1000.0,
                    "\u00A51000"
                ),
                MoneyPiece(
                    "JPYPaper5000",
                    5000.0,
                    "\u00A55000"
                ),
                MoneyPiece(
                    "JPYPaper10000",
                    10000.0,
                    "\u00A510000"
                )
            ),
            arrayOf(
                MoneyPiece(
                    "JPYPaper2000",
                    2000.0,
                    "\u00A52000"
                )
            ),
            arrayOf(
                MoneyPiece(
                    "JPYCoin1",
                    1.0,
                    "\u00A51"
                ),
                MoneyPiece(
                    "JPYCoin5",
                    5.0,
                    "\u00A55"
                ),
                MoneyPiece(
                    "JPYCoin10",
                    10.0,
                    "\u00A510"
                ),
                MoneyPiece(
                    "JPYCoin50",
                    50.0,
                    "\u00A550"
                ),
                MoneyPiece(
                    "JPYCoin100",
                    100.0,
                    "\u00A5100"
                ),
                MoneyPiece(
                    "JPYCoin500",
                    500.0,
                    "\u00A5500"
                )
            )
        ),

        //mexican dollar
        Currency(
            "MXN",
            "Mexican Peso",
            "$",
            arrayOf(
                MoneyPiece(
                    "MXNPaper20",
                    20.0,
                    "$20"
                ),
                MoneyPiece(
                    "MXNPaper50",
                    50.0,
                    "$50"
                ),
                MoneyPiece(
                    "MXNPaper100",
                    100.0,
                    "$100"
                )
            ),
            arrayOf(
                MoneyPiece(
                    "MXNPaper200",
                    200.0,
                    "$200"
                ),
                MoneyPiece(
                    "MXNPaper500",
                    500.0,
                    "$500"
                ),
                MoneyPiece(
                    "MXNPaper1000",
                    1000.0,
                    "$1000"
                )
            ),
            arrayOf(
                MoneyPiece(
                    "MXNCoin50",
                    0.5,
                    "50\u00A2"
                ),
                MoneyPiece(
                    "MXNCoin100",
                    1.0,
                    "$1"
                ),
                MoneyPiece(
                    "MXNCoin200",
                    2.0,
                    "$2"
                ),
                MoneyPiece(
                    "MXNCoin500",
                    5.0,
                    "$5"
                ),
                MoneyPiece(
                    "MXNCoin1000",
                    10.0,
                    "$10"
                ),
                MoneyPiece(
                    "MXNCoin2000",
                    20.0,
                    "$20"
                ),
                MoneyPiece(
                    "MXNCoin5",
                    0.05,
                    "5\u00A2"
                ),
                MoneyPiece(
                    "MXNCoin10",
                    0.1,
                    "10\u00A2"
                ),
                MoneyPiece(
                    "MXNCoin20",
                    0.2,
                    "20\u00A2"
                ),
                MoneyPiece(
                    "MXNCoin25",
                    0.25,
                    "25\u00A2"
                ),
                MoneyPiece(
                    "MXNCoin2500",
                    25.0,
                    "$25"
                )
            )
        )
    )

    fun getCurrency(name: String): Currency {
        for (c: Currency in list) {
            if (c.uniqueIdentifier == name) {
                return c
            }
        }

        return Currency("ERR", "ERR", "ERR", arrayOf(), arrayOf(), arrayOf())
    }
}